shoulder_length: 0.055
arm_length: 0.105
forearm_length: 0.136
body_width: 0.038
center_to_front: 0.1
center_to_back: 0.1
frequency: 30.0
walking_height: 0.14
step_height: 0.04
leg_x_offset: -0.045
leg_x_separation: 0.07
leg_y_separation: 0.00