shoulder_length: 0.055
arm_length: 0.105
forearm_length: 0.136
body_width: 0.08
center_to_front: 0.12
center_to_back: 0.12
frequency: 15.0
walking_height: 0.16
step_height: 0.04
leg_x_offset: -0.045
leg_x_separation: 0.07
leg_y_separation: 0.00